/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kkp;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

public class Form_Enkripsi extends javax.swing.JFrame {

    ImageIcon img;
    private static int kd_file;
    
    public Form_Enkripsi() {
        initComponents();
        img = new ImageIcon("src/gambar/logo.jpg");
        setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPilihFile = new javax.swing.JTextField();
        txtKunciPublic = new javax.swing.JTextField();
        txtSave = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();
        btnpilihfile = new javax.swing.JButton();
        btnpilihkunci = new javax.swing.JButton();
        btnEnkrip = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Form Enkripsi");

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 390));
        jPanel1.setPreferredSize(new java.awt.Dimension(474, 302));

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pilih File              :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Kunci Publik       :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tempat Simpan :");

        txtPilihFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtKunciPublic.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnsimpan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/save2.png"))); // NOI18N
        btnsimpan.setText("Simpan");
        btnsimpan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        btnpilihfile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpilihfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/folder-yellow-explorer-icon2.png"))); // NOI18N
        btnpilihfile.setText("Pilih");
        btnpilihfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihfileActionPerformed(evt);
            }
        });

        btnpilihkunci.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnpilihkunci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/folder-yellow-explorer-icon2.png"))); // NOI18N
        btnpilihkunci.setText("Pilih");
        btnpilihkunci.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnpilihkunci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpilihkunciActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtKunciPublic, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPilihFile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnpilihkunci, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpilihfile, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsimpan))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPilihFile, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnpilihfile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKunciPublic, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnpilihkunci))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnsimpan))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnEnkrip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/lock-icon2.png"))); // NOI18N
        btnEnkrip.setText("Enkrip");
        btnEnkrip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnkrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnkripActionPerformed(evt);
            }
        });

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/clear2.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/cancel-icon2.png"))); // NOI18N
        btnKeluar.setText("Kembali");
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/MAN 12 Jakarta.jpg"))); // NOI18N
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel7.setPreferredSize(new java.awt.Dimension(600, 166));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnkrip, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed
        // TODO add your handling code here:
      if(!(txtPilihFile.getText().equals("") && txtKunciPublic.getText().equals(""))){
          try{
              JFileChooser chooser = new JFileChooser("D:\\") {
            public void approveSelection() {
                if (getSelectedFile().isFile()) {
                    return;
                } else {
                    super.approveSelection();
                }
            }
        };
        chooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                File directory = chooser.getSelectedFile();
                txtSave.setText(directory.getAbsolutePath() );
            } catch (Exception except) {
                //msg if opening failsAT
                JOptionPane.showMessageDialog(this, "File Tidak Sesuai!","Attention", JOptionPane.ERROR_MESSAGE);
                txtSave.setText("");
            }
        }
          }catch(Exception e){
              
          }
      }else {
          JOptionPane.showMessageDialog(this, "Silahkan Isi Form Terlebih Dahulu !","Attention", JOptionPane.ERROR_MESSAGE);
      }
        
    }//GEN-LAST:event_btnsimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        MenuUtama menu;
        try {
            menu = new MenuUtama();
            menu.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Form_Enkripsi.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnpilihfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihfileActionPerformed
        // TODO add your handling code here:
        JFileChooser datafile = new JFileChooser("D:\\");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("File Document","doc","docx","xls","xlsx","pdf","txt");

        datafile.setFileFilter(filter);
         datafile.setAcceptAllFileFilterUsed(false);
        int returnVal = datafile.showOpenDialog(null);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            File file = datafile.getSelectedFile();
            String dir = file.getAbsolutePath(); 
            txtPilihFile.setText(dir);
            
        }      
    }//GEN-LAST:event_btnpilihfileActionPerformed

    private void btnpilihkunciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpilihkunciActionPerformed
        // TODO add your handling code here:
        if(!(txtPilihFile.getText().equals(""))){
           JFileChooser dataFile = new JFileChooser("D:\\");
       
            FileNameExtensionFilter filter = new FileNameExtensionFilter("public key", "PublicKey");
            dataFile.setFileFilter(filter);
            dataFile.setAcceptAllFileFilterUsed(false);
            int returnVal = dataFile.showOpenDialog(null);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = dataFile.getSelectedFile();
                String dir = file.getAbsolutePath();
                txtKunciPublic.setText(dir);
            }
       }else {
            JOptionPane.showMessageDialog(null, "Silahkan Pilih File Terlebih Dahulu !","Attention", JOptionPane.ERROR_MESSAGE);
            txtPilihFile.requestFocus();
       }
    }//GEN-LAST:event_btnpilihkunciActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEnkripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnkripActionPerformed
        // TODO add your handling code here:
        enkrip();
    }//GEN-LAST:event_btnEnkripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Enkripsi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Enkripsi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnkrip;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnpilihfile;
    private javax.swing.JButton btnpilihkunci;
    private javax.swing.JButton btnsimpan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtKunciPublic;
    private javax.swing.JTextField txtPilihFile;
    private javax.swing.JTextField txtSave;
    // End of variables declaration//GEN-END:variables

    private void bersih(){
        txtPilihFile.setText("");
        txtKunciPublic.setText("");
        txtSave.setText("");
    } 
    
    private void enkrip(){
        Thread t =  new Thread(new Runnable(){
            @Override
            public void run(){
                String namaFile = (txtPilihFile.getText());
               
                File file = new File(txtPilihFile.getText());
                String save = (txtSave.getText());
                String KunciPublic = (txtKunciPublic.getText());
                String totalWaktu;
                long start, end;
                koneksi koneksi = new koneksi();
                double ukuran = file.length()/1024;
               
                    Enkrip_Dekrip elgamal = new Enkrip_Dekrip();
                    
                    if (!(KunciPublic.equals("") || namaFile.equals("") || save.equals(""))) {
                    try {
                        btnEnkrip.setEnabled(false);
                        btnHapus.setEnabled(false);
                        btnKeluar.setEnabled(false);
                        btnpilihfile.setEnabled(false);
                        btnpilihkunci.setEnabled(false);
                        btnsimpan.setEnabled(false);
                        txtKunciPublic.setEnabled(false);
                        txtPilihFile.setEnabled(false);
                        txtSave.setEnabled(false);
                        //tambahan batasan maksimu file
                        if(file.length()/1024>1024){
                            JOptionPane.showMessageDialog(null, "File Tidak Boleh Lebih Dari 1 MB", "Peringatan", JOptionPane.ERROR_MESSAGE);
                            bersih();
                            btnEnkrip.setEnabled(true);
                            btnHapus.setEnabled(true);
                            btnKeluar.setEnabled(true);
                            btnpilihfile.setEnabled(true);
                            btnpilihkunci.setEnabled(true);
                            btnsimpan.setEnabled(true);
                            txtKunciPublic.setEnabled(true);
                            txtPilihFile.setEnabled(true);
                            txtSave.setEnabled(true);
                        }else{
                        
                        start = System.currentTimeMillis();
                       //========== Membaca Public Key pada notepad ===========
                            elgamal.setPublicKey(KunciPublic);
                            elgamal.enkrip(file, save, namaFile);
                        end = System.currentTimeMillis();
                        totalWaktu = String.valueOf((end - start)/1000.0);
                        JOptionPane.showMessageDialog(null, "Proses Enkripsi Sudah Selesai dengan Waktu "+totalWaktu+" Detik" 
                                ,"PESAN", JOptionPane.INFORMATION_MESSAGE);
                        
                        btnEnkrip.setEnabled(true);
                        btnHapus.setEnabled(true);
                        btnKeluar.setEnabled(true);
                        btnpilihfile.setEnabled(true);
                        btnpilihkunci.setEnabled(true);
                        btnsimpan.setEnabled(true);
                        txtKunciPublic.setEnabled(true);
                        txtPilihFile.setEnabled(true);
                        txtSave.setEnabled(true);
                        kd_file = Session.get_row();
                        kd_file = kd_file+1;
                        String kd = String.valueOf(kd_file);
                        if(kd.length()==1)kd="F00"+kd;
                        else if (kd.length()==2)kd="F0"+kd;
                        else if (kd.length()==3)kd="F"+kd;
                        String user = Session.get_kd_user();
                        
                     
                        Connection con = koneksi.bukaKoneksi();
                        Statement st = con.createStatement();
                        st.executeUpdate("insert into laporan values('"+kd+"','"+file.getName()+"','"+ukuran+"','Enkripsi','"+totalWaktu+"','"+user+"')");
                        System.out.println("Data Tersimpan ke Dalam Database"); 
                      
                        st.close();
                        
                        
                        //bersih();
                        
                        }
                       
                    }catch (IOException ex) {
                        Logger.getLogger(Form_Enkripsi.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Form_Enkripsi.class.getName()).log(Level.SEVERE, null, ex);
                    } 
                  } else {
                        JOptionPane.showMessageDialog(null, "Silahkan Lengkapi Form Terlebih Dahulu", "Peringatan", JOptionPane.ERROR_MESSAGE);
                        //bersih();
                        }
                        }

                    });
                    t.start();
        }
    }

